export const FALLBACK_TAGS = [
  { label: "bang", cluster: "angst", level: 0, relations: [{ toLabel: "opgejaagd", strength: 0.92 }, { toLabel: "controle kwijt", strength: 0.78 }, { toLabel: "onveilig", strength: 0.74 }] },
  { label: "leeg", cluster: "zelfbeeld", level: 0, relations: [{ toLabel: "verdoofd", strength: 0.9 }, { toLabel: "niets voelen", strength: 0.82 }, { toLabel: "verdwijnen", strength: 0.66 }] },
  { label: "boos", cluster: "emoties", level: 0, relations: [{ toLabel: "onrecht", strength: 0.86 }, { toLabel: "niet gehoord", strength: 0.82 }, { toLabel: "ontploffen", strength: 0.72 }] },
  { label: "moe", cluster: "lichaam", level: 0, relations: [{ toLabel: "uitgeput", strength: 0.88 }, { toLabel: "geen ruimte", strength: 0.76 }, { toLabel: "slaap", strength: 0.7 }] },
  { label: "alleen", cluster: "eenzaamheid", level: 0, relations: [{ toLabel: "niemand begrijpt mij", strength: 0.88 }, { toLabel: "buitengesloten", strength: 0.74 }, { toLabel: "stilte", strength: 0.62 }] },
  { label: "te veel", cluster: "prikkels", level: 0, relations: [{ toLabel: "overprikkeld", strength: 0.92 }, { toLabel: "drukte", strength: 0.72 }, { toLabel: "hoofd vol", strength: 0.7 }] },
  { label: "niet genoeg", cluster: "zelfbeeld", level: 0, relations: [{ toLabel: "falen", strength: 0.82 }, { toLabel: "schaamte", strength: 0.78 }, { toLabel: "mezelf kwijt", strength: 0.68 }] },
  { label: "verdoofd", cluster: "trauma", level: 0, relations: [{ toLabel: "niets voelen", strength: 0.9 }, { toLabel: "afstand", strength: 0.72 }, { toLabel: "weg zijn", strength: 0.66 }] },
  { label: "opgejaagd", cluster: "angst", level: 0, relations: [{ toLabel: "rusteloos", strength: 0.86 }, { toLabel: "paniek", strength: 0.72 }, { toLabel: "haast", strength: 0.64 }] },
  { label: "klem", cluster: "werk", level: 0, relations: [{ toLabel: "geen uitweg", strength: 0.84 }, { toLabel: "moeten", strength: 0.78 }, { toLabel: "vastlopen", strength: 0.7 }] },
  { label: "partner", cluster: "relaties", level: 0, relations: [{ toLabel: "afstand", strength: 0.78 }, { toLabel: "ruzie", strength: 0.74 }, { toLabel: "verlaten worden", strength: 0.7 }] },
  { label: "ouders", cluster: "familie", level: 0, relations: [{ toLabel: "verwachtingen", strength: 0.76 }, { toLabel: "oude pijn", strength: 0.74 }, { toLabel: "niet gezien", strength: 0.68 }] },
  { label: "werk", cluster: "werk", level: 0, relations: [{ toLabel: "druk", strength: 0.82 }, { toLabel: "maskeren", strength: 0.72 }, { toLabel: "vastlopen", strength: 0.68 }] },
  { label: "ADHD", cluster: "neurodiversiteit", level: 0, relations: [{ toLabel: "hoofd vol", strength: 0.82 }, { toLabel: "uitstel", strength: 0.72 }, { toLabel: "snel afgeleid", strength: 0.68 }] },
  { label: "autisme", cluster: "neurodiversiteit", level: 0, relations: [{ toLabel: "overprikkeld", strength: 0.84 }, { toLabel: "maskeren", strength: 0.78 }, { toLabel: "verandering", strength: 0.64 }] },
  { label: "misbruik", cluster: "trauma", level: 0, relations: [{ toLabel: "onveilig", strength: 0.9 }, { toLabel: "oude pijn", strength: 0.8 }, { toLabel: "lichaam herinnert", strength: 0.72 }] },
  { label: "alcohol", cluster: "verslaving", level: 0, relations: [{ toLabel: "verdoven", strength: 0.84 }, { toLabel: "spijt", strength: 0.76 }, { toLabel: "controle kwijt", strength: 0.7 }] },
  { label: "eten", cluster: "lichaam", level: 0, relations: [{ toLabel: "controle", strength: 0.72 }, { toLabel: "schaamte", strength: 0.7 }, { toLabel: "lichaam", strength: 0.62 }] },
  { label: "overprikkeld", cluster: "prikkels", level: 1, relations: [{ toLabel: "licht", strength: 0.72 }, { toLabel: "geluid", strength: 0.72 }, { toLabel: "alleen willen zijn", strength: 0.68 }] },
  { label: "hoofd vol", cluster: "neurodiversiteit", level: 1, relations: [{ toLabel: "chaos", strength: 0.76 }, { toLabel: "uitstel", strength: 0.66 }, { toLabel: "vergeten", strength: 0.58 }] },
  { label: "verlaten worden", cluster: "relaties", level: 1, relations: [{ toLabel: "vastklampen", strength: 0.74 }, { toLabel: "afstand voelen", strength: 0.72 }, { toLabel: "paniek in relatie", strength: 0.7 }] },
  { label: "oude pijn", cluster: "trauma", level: 1, relations: [{ toLabel: "trigger", strength: 0.76 }, { toLabel: "herinneringen", strength: 0.7 }, { toLabel: "lichaam herinnert", strength: 0.66 }] },
  { label: "schaamte", cluster: "zelfbeeld", level: 1, relations: [{ toLabel: "verbergen", strength: 0.76 }, { toLabel: "niet goed genoeg", strength: 0.72 }, { toLabel: "klein worden", strength: 0.62 }] },
  { label: "druk", cluster: "werk", level: 1, relations: [{ toLabel: "moeten", strength: 0.82 }, { toLabel: "geen ruimte", strength: 0.7 }, { toLabel: "opbranden", strength: 0.66 }] },
  { label: "maskeren", cluster: "neurodiversiteit", level: 1, relations: [{ toLabel: "uitputting", strength: 0.78 }, { toLabel: "niet mezelf", strength: 0.7 }, { toLabel: "aanpassen", strength: 0.66 }] },
  { label: "onveilig", cluster: "trauma", level: 1, relations: [{ toLabel: "alert", strength: 0.74 }, { toLabel: "bevriezen", strength: 0.7 }, { toLabel: "niet vertrouwen", strength: 0.62 }] },
  { label: "geen ruimte", cluster: "lichaam", level: 1, relations: [{ toLabel: "adem tekort", strength: 0.7 }, { toLabel: "op", strength: 0.66 }, { toLabel: "stil willen", strength: 0.6 }] },
  { label: "niet gehoord", cluster: "relaties", level: 1, relations: [{ toLabel: "uitleggen", strength: 0.68 }, { toLabel: "onzichtbaar", strength: 0.66 }, { toLabel: "afstand", strength: 0.58 }] },
  { label: "ruzie", cluster: "relaties", level: 1, relations: [{ toLabel: "woorden spijt", strength: 0.66 }, { toLabel: "stilvallen", strength: 0.62 }, { toLabel: "terugtrekken", strength: 0.58 }] },
  { label: "uitstel", cluster: "neurodiversiteit", level: 1, relations: [{ toLabel: "schuldgevoel", strength: 0.68 }, { toLabel: "vastlopen", strength: 0.66 }, { toLabel: "starten lukt niet", strength: 0.64 }] },
  { label: "paniek", cluster: "angst", level: 1, relations: [{ toLabel: "hart snel", strength: 0.66 }, { toLabel: "vluchten", strength: 0.62 }, { toLabel: "controle kwijt", strength: 0.6 }] },
  { label: "verdoven", cluster: "verslaving", level: 1, relations: [{ toLabel: "niet voelen", strength: 0.7 }, { toLabel: "spijt", strength: 0.62 }, { toLabel: "alleen daarna", strength: 0.56 }] },
  { label: "controle kwijt", cluster: "angst", level: 1, relations: [{ toLabel: "bang van mezelf", strength: 0.66 }, { toLabel: "te snel", strength: 0.6 }, { toLabel: "stoppen lukt niet", strength: 0.58 }] },
  { label: "niet gezien", cluster: "familie", level: 1, relations: [{ toLabel: "klein kind", strength: 0.62 }, { toLabel: "oude rol", strength: 0.6 }, { toLabel: "verwachtingen", strength: 0.58 }] },
  { label: "verwachtingen", cluster: "familie", level: 1, relations: [{ toLabel: "moeten voldoen", strength: 0.64 }, { toLabel: "schuld", strength: 0.58 }, { toLabel: "grenzen", strength: 0.56 }] },
  { label: "vastlopen", cluster: "werk", level: 1, relations: [{ toLabel: "geen begin", strength: 0.66 }, { toLabel: "te groot", strength: 0.62 }, { toLabel: "opgeven", strength: 0.54 }] },
  { label: "niets voelen", cluster: "trauma", level: 1, relations: [{ toLabel: "weg zijn", strength: 0.7 }, { toLabel: "afstand", strength: 0.64 }, { toLabel: "automatisch doorgaan", strength: 0.58 }] },
  { label: "intense emoties", cluster: "emoties", level: 0, relations: [{ toLabel: "snel overspoeld", strength: 0.78 }, { toLabel: "alles of niets", strength: 0.68 }, { toLabel: "ontploffen", strength: 0.62 }] },
  { label: "snel overspoeld", cluster: "emoties", level: 1, relations: [{ toLabel: "te veel voelen", strength: 0.72 }, { toLabel: "huilen", strength: 0.6 }, { toLabel: "weg willen", strength: 0.58 }] },
  { label: "grenzen", cluster: "relaties", level: 1, relations: [{ toLabel: "nee zeggen", strength: 0.68 }, { toLabel: "schuld", strength: 0.62 }, { toLabel: "pleasen", strength: 0.58 }] }
];

export const INITIAL_TAG_LABELS = ["bang", "leeg", "boos", "moe", "alleen", "te veel", "niet genoeg", "klem", "partner", "ouders"];